import { App, Notice, Plugin, TFile, TFolder, normalizePath } from "obsidian";
import { deduplicateNewName } from "./lib/deduplicate";
import { path } from "./lib/path";
import { debugLog } from "./lib/log";
import { AttachmentManagementPluginSettings } from "./settings/settings";
import { getOverrideSetting } from "./override";
import { getMetadata } from "./settings/metadata";
import { isExcluded } from "./exclude";
import { getExtensionOverrideSetting } from "./model/extensionOverride";
import { md5sum, isImage, isPastedImage, isAutoGeneratedImage, getVisionMimeType, arrayBufferToBase64, extractSourceAppHint } from "./utils";
import { saveOriginalName } from "./lib/originalStorage";
import { extractNoteContext, generateAiFileName } from "./lib/ai";
import { saveAiName } from "./lib/aiStorage";

export class CreateHandler {
  readonly plugin: Plugin;
  readonly app: App;
  readonly settings: AttachmentManagementPluginSettings;

  constructor(plugin: Plugin, settings: AttachmentManagementPluginSettings) {
    this.plugin = plugin;
    this.app = this.plugin.app;
    this.settings = settings;
  }

  /**
   * Post-processing of created attachment file (for paste and drop event).
   * Refactored to async/await for clarity and to support the AI rename step.
   *
   * @param attach - the attachment file to process
   * @param source - the notes file that linked to attach
   * @param noteContent - full text content of the source note (optional)
   * @param linkText - the markdown link text for the attachment (optional)
   */
  async processAttach(
    attach: TFile,
    source: TFile,
    noteContent?: string,
    linkText?: string
  ): Promise<void> {
    debugLog("processAttach - START, attach:", attach.path, "name:", attach.name, "source:", source.path);
    debugLog("processAttach - noteContent length:", noteContent?.length ?? 0, "linkText:", linkText);

    // Ignore if the path of notes file has been excluded
    if (source.parent && isExcluded(source.parent.path, this.settings)) {
      debugLog("processAttach - not a file or exclude path:", source.path);
      new Notice(`${source.path} was excluded from attachment management.`);
      return;
    }

    // Get override setting for the notes file or extension
    const { setting } = getOverrideSetting(this.settings, source);
    const { extSetting } = getExtensionOverrideSetting(attach.extension, setting);

    debugLog("processAttach - file.extension:", attach.extension, "extSetting:", extSetting);
    debugLog("processAttach - isImage:", isImage(attach.extension), "isPastedImage:", isPastedImage(attach));
    if (extSetting === undefined && !isImage(attach.extension) && !isPastedImage(attach)) {
      debugLog("renameFiles - no handle extension:", attach.extension);
      return;
    }

    const metadata = getMetadata(source.path, attach);
    debugLog("processAttach - metadata:", metadata);

    const attachPath = metadata.getAttachmentPath(setting, this.settings.dateFormat);
    let attachName = await metadata.getAttachFileName(
      setting,
      this.settings.dateFormat,
      attach.basename,
      this.app.vault.adapter
    );
    debugLog("processAttach - template attachPath:", attachPath, "template attachName:", attachName);

    // AI rename step: only for Markdown + pasted images when AI is configured
    let aiGeneratedName: string | null = null;
    const aiEnabled = this.shouldUseAi(attach, source, noteContent);
    debugLog("processAttach - shouldUseAi:", aiEnabled);
    if (aiEnabled) {
      aiGeneratedName = await this.tryAiRename(attach, source, noteContent!, linkText);
      debugLog("processAttach - AI result:", aiGeneratedName);
      if (aiGeneratedName) {
        attachName = aiGeneratedName;
        debugLog("processAttach - using AI name:", attachName);
      }
    }

    attachName = attachName + "." + attach.extension;
    debugLog("processAttach - final attachName:", attachName);

    // Ensure the attachment path exists
    const exists = await this.app.vault.adapter.exists(attachPath, true);
    if (!exists) {
      await this.app.vault.adapter.mkdir(attachPath);
      debugLog("processAttach - create path:", attachPath);
    }

    // Deduplicate the filename if needed
    const attachPathFolder = this.app.vault.getAbstractFileByPath(attachPath) as TFolder;
    const { name: dedupName } = await deduplicateNewName(attachName, attachPathFolder);
    debugLog("processAttach - new path of file:", path.join(attachPath, dedupName));

    await this.renameCreateFile(attach, attachPath, dedupName, source, aiGeneratedName);
  }

  /**
   * Checks whether AI rename should be attempted for this attachment.
   */
  private shouldUseAi(
    attach: TFile,
    source: TFile,
    noteContent?: string
  ): boolean {
    const ai = this.settings.aiRename;
    debugLog("shouldUseAi - checks:",
      "enabled:", ai.enabled,
      "apiKey:", !!ai.apiKey,
      "apiEndpoint:", !!ai.apiEndpoint,
      "source.ext:", source.extension,
      "isPasted:", isPastedImage(attach),
      "isAutoGenerated:", isAutoGeneratedImage(attach),
      "attach.name:", attach.name,
      "hasContent:", !!noteContent
    );
    return (
      ai.enabled &&
      !!ai.apiKey &&
      !!ai.apiEndpoint &&
      source.extension === "md" &&
      isAutoGeneratedImage(attach) &&
      !!noteContent
    );
  }

  /**
   * Attempts to generate a filename using the AI service.
   * Returns the sanitized name on success, null on failure.
   */
  private async tryAiRename(
    attach: TFile,
    source: TFile,
    noteContent: string,
    linkText?: string
  ): Promise<string | null> {
    try {
      debugLog("tryAiRename - START, attach:", attach.name, "source:", source.path);
      const context = extractNoteContext(
        noteContent,
        linkText ?? "",
        source.basename
      );

      // Extract source app name from original filename (e.g. "Google Chrome")
      const sourceHint = extractSourceAppHint(attach.basename);
      if (sourceHint) {
        context.sourceAppHint = sourceHint;
      }

      // Attach image content for vision-capable models if enabled
      if (this.settings.aiRename.sendImageContent) {
        const mimeType = getVisionMimeType(attach.extension);
        if (mimeType) {
          const sizeMB = attach.stat.size / (1024 * 1024);
          const maxMB = this.settings.aiRename.maxImageSizeMB || 4;
          if (sizeMB > maxMB) {
            debugLog("tryAiRename - image too large for vision, skipping:", sizeMB.toFixed(1), "MB");
          } else {
            const buffer = await this.app.vault.readBinary(attach);
            context.imageBase64 = arrayBufferToBase64(buffer);
            context.imageMimeType = mimeType;
            debugLog("tryAiRename - attached image:", mimeType, sizeMB.toFixed(1), "MB");
          }
        } else {
          debugLog("tryAiRename - vision unsupported for extension:", attach.extension);
        }
      }

      // Reason: Log context without imageBase64 to avoid dumping megabytes of data
      const { imageBase64: _omitted, ...contextForLog } = context;
      debugLog("tryAiRename - context:", JSON.stringify(contextForLog),
        context.imageBase64 ? `(image: ${context.imageMimeType})` : "(no image)");

      // Reason: Timeout is now handled inside generateAiFileName via requestUrlWithTimeout
      const aiName = await generateAiFileName(this.settings.aiRename, context);

      debugLog("tryAiRename - AI returned:", aiName);
      if (!aiName) {
        debugLog("tryAiRename - AI returned no valid name, falling back to template");
      }
      return aiName;
    } catch (err) {
      debugLog("tryAiRename - error:", err);
      return null;
    }
  }

  /**
   * Rename the file specified by `@param attach`, and update the link.
   * Persists original name and AI name storage only on successful rename.
   *
   * @param attach - file to rename
   * @param attachPath - where the renamed file will be moved to
   * @param attachName - name of the renamed file
   * @param source - associated active file
   * @param aiName - AI-generated basename if applicable, null otherwise
   */
  private async renameCreateFile(
    attach: TFile,
    attachPath: string,
    attachName: string,
    source: TFile,
    aiName: string | null
  ): Promise<void> {
    const dst = normalizePath(path.join(attachPath, attachName));
    debugLog("renameCreateFile - src:", attach.path, "dst:", dst);
    debugLog("renameCreateFile - aiName:", aiName);

    const original = attach.basename;
    const name = attach.name;

    try {
      debugLog("renameCreateFile - calling renameFile...");
      await this.app.fileManager.renameFile(attach, dst);
      debugLog("renameCreateFile - rename SUCCESS");
      new Notice(`Renamed ${name} to ${attachName}.`);

      // Persist original name and AI name only after successful rename
      const { setting } = getOverrideSetting(this.settings, source);
      const md5 = await md5sum(this.app.vault.adapter, attach);

      saveOriginalName(this.settings, setting, attach.extension, {
        n: original,
        md5: md5,
      });

      // Fill empty alt text with the new basename (general feature, not AI-specific)
      if (this.settings.autoFillAltText) {
        const altText = aiName ?? attach.basename;
        await this.fillAltText(source, attachName, altText);
      }

      // Save AI-generated name for rearrange preservation
      if (aiName) {
        if (!this.settings.aiNameStorage) {
          this.settings.aiNameStorage = [];
        }
        saveAiName(this.settings.aiNameStorage, {
          md5,
          sourcePath: source.path,
          name: aiName,
        });
      }

      await this.plugin.saveData(this.settings);
    } catch (err) {
      debugLog("renameCreateFile - rename failed:", err);
    }
  }

  /**
   * Fills empty alt text in markdown/wikilink references with the AI name.
   * Handles both standard markdown `![](file.png)` → `![ai-name](file.png)`
   * and wikilinks `![[file.png]]` → `![[file.png|ai-name]]`.
   */
  private async fillAltText(
    source: TFile,
    attachName: string,
    altText: string
  ): Promise<void> {
    try {
      const content = await this.app.vault.cachedRead(source);
      // Reason: attachName may contain spaces or special regex chars from the path.
      const escaped = attachName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

      // Reason: Escape syntax-breaking characters in alt text to prevent
      // malformed markdown/wikilinks when basename contains ] ) or |.
      const markdownAltText = altText
        .replace(/\\/g, "\\\\")
        .replace(/]/g, "\\]");
      const wikilinkAltText = altText
        .replace(/\|/g, "-")
        .replace(/]/g, "")
        .trim();

      let updated = content;

      // Reason: Use replacer functions instead of template strings to avoid
      // $ characters in altText being interpreted as regex replacement tokens.

      // Standard markdown: ![](path/to/file.png) → ![alt-text](path/to/file.png)
      updated = updated.replace(
        new RegExp(`!\\[\\]\\(([^)]*${escaped})\\)`, "g"),
        (_, p1) => `![${markdownAltText}](${p1})`
      );

      // Wikilinks without alias: ![[file.png]] → ![[file.png|alt-text]]
      if (wikilinkAltText.length > 0) {
        updated = updated.replace(
          new RegExp(`!\\[\\[([^\\]]*${escaped})\\]\\]`, "g"),
          (_, p1) => `![[${p1}|${wikilinkAltText}]]`
        );
      }

      if (updated !== content) {
        await this.app.vault.modify(source, updated);
        debugLog("fillAltText - filled alt text with:", altText);
      }
    } catch (err) {
      debugLog("fillAltText - failed:", err);
    }
  }
}
