import { DataAdapter, Notice, TAbstractFile, TFile } from "obsidian";
import { AttachmentManagementPluginSettings, AttachmentPathSettings } from "./settings/settings";
import { t } from "./i18n/index";

import { Md5 } from "ts-md5";

const PASTED_IMAGE_PREFIX = "Pasted image ";
const ImageExtensionRegex = /^(jpe?g|png|gif|svg|bmp|eps|webp)$/i;

// Reason: macOS screenshots use "<AppName> YYYY-MM-DD HH.MM.SS" format,
// CleanShot uses "<AppName> YYYY-MM-DD at HH.MM.SS" format,
// Windows uses "Screenshot YYYY-MM-DD", Obsidian uses "Pasted image YYYY..."
// The optional "at" handles CleanShot and similar tools.
const AUTO_GENERATED_IMAGE_REGEX = /\d{4}-\d{2}-\d{2}[\s_.]+(?:at[\s_.]+)?\d{2}[\s_.]+\d{2}[\s_.]+\d{2}/;

// Reason: These prefixes indicate screenshot tools or generic paste names.
// They carry no meaningful content info and should be excluded from AI hints.
const SCREENSHOT_TOOL_PREFIXES = [
  "cleanshot", "snipaste", "greenshot", "snagit",
  "lightshot", "flameshot", "shottr", "xnapper",
  "capto", "ksnip", "pasted image", "screenshot", "screen shot",
];

// Broader regex for extracting the date-time position in auto-generated filenames.
// Supports YYYY-MM-DD with optional time, and optional "at" separator.
const TIMESTAMP_REGEX = /\d{4}-\d{2}-\d{2}[\s_.]+(?:at[\s_.]+)?(?:\d{2}[\s_.]+\d{2}[\s_.]+\d{2})?/;

// Reason: Only these formats are reliably supported by OpenAI-compatible vision APIs.
// svg/eps/bmp are excluded — they either lack broad support or produce poor results.
const VISION_MIME_MAP: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
  gif: "image/gif",
};

export const blobToArrayBuffer = (blob: Blob) => {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.readAsArrayBuffer(blob);
  });
};

export function isMarkdownFile(extension: string): boolean {
  return extension === "md";
}

export function isCanvasFile(extension: string): boolean {
  return extension === "canvas";
}

export function isPastedImage(file: TAbstractFile): boolean {
  if (file instanceof TFile) {
    if (file.name.startsWith(PASTED_IMAGE_PREFIX)) {
      return true;
    }
  }
  return false;
}

/**
 * Checks if an image file has an auto-generated name (screenshot or paste).
 * Covers: Obsidian "Pasted image ...", macOS "AppName YYYY-MM-DD HH.MM.SS",
 * Windows "Screenshot YYYY-MM-DD ...", and similar timestamp-based names.
 */
export function isAutoGeneratedImage(file: TAbstractFile): boolean {
  if (!(file instanceof TFile) || !isImage(file.extension)) {
    return false;
  }
  if (file.name.startsWith(PASTED_IMAGE_PREFIX)) {
    return true;
  }
  if (file.name.toLowerCase().startsWith("screenshot")) {
    return true;
  }
  // Match filenames containing date-time pattern like "2026-03-22 01.43.44"
  return AUTO_GENERATED_IMAGE_REGEX.test(file.basename);
}

/**
 * Returns the MIME type for vision-supported image formats, null otherwise.
 * Unsupported formats (svg, eps, bmp) return null to trigger text-only fallback.
 */
export function getVisionMimeType(extension: string): string | null {
  return VISION_MIME_MAP[extension.toLowerCase()] ?? null;
}

/**
 * Converts an ArrayBuffer to a base64-encoded string.
 * Uses chunked processing to avoid stack overflow on large images.
 */
export function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;
  let binary = "";
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
  }
  return btoa(binary);
}

/**
 * Extracts a meaningful source app name from an auto-generated image basename.
 * Returns null when the filename is from a screenshot tool or has no useful info.
 *
 * "Google Chrome 2026-03-26 17.30.54" → "Google Chrome"
 * "CleanShot 2026-03-26 at 17.33.30"  → null
 * "Pasted image 20260326"             → null
 * "Arc 2026-03-26 17.30.54"           → "Arc"
 */
export function extractSourceAppHint(basename: string): string | null {
  const normalized = basename.trim().toLowerCase();

  // Check if the filename starts with a known screenshot tool prefix
  for (const prefix of SCREENSHOT_TOOL_PREFIXES) {
    if (normalized.startsWith(prefix)) {
      return null;
    }
  }

  // Find timestamp position and extract the text before it
  const match = TIMESTAMP_REGEX.exec(basename);
  if (!match) {
    return null;
  }

  let candidate = basename.substring(0, match.index).replace(/[-_([)\]\s]+$/, "").trim();

  // Reject empty, pure-digit, or too-short-to-be-meaningful results
  if (!candidate || /^\d+$/.test(candidate)) {
    return null;
  }

  return candidate;
}

export function isImage(extension: string): boolean {
  const match = extension.match(ImageExtensionRegex);
  if (match !== null) {
    return true;
  }
  return false;
}

/**
 * find the first prefix difference of two paths
 * e.g.:
 *   "Resources/Untitled/Untitled 313/Untitled"
 *   "Resources/Untitled1/Untitled 313/Untitled"
 * result:
 *   "Resources/Untitled"
 *   "Resources/Untitled1"
 * @param src source path
 * @param dst destination path
 * @returns the first different prefix, otherwise, return the original path
 */
export function stripPaths(src: string, dst: string): { stripedSrc: string; stripedDst: string } {
  if (src === dst) {
    return { stripedSrc: src, stripedDst: dst };
  }

  const srcParts = src.split("/");
  const dstParts = dst.split("/");

  // if src and dst have difference count of parts,
  // we think the paths was not in a same parent folder and no need to strip the prefix
  if (srcParts.length !== dstParts.length) {
    return { stripedSrc: src, stripedDst: dst };
  }

  for (let i = 0; i < srcParts.length; i++) {
    const srcPart = srcParts[i];
    const dstPart = dstParts[i];

    // find the first different part
    if (srcPart !== dstPart) {
      return {
        stripedSrc: srcParts.slice(0, i + 1).join("/"),
        stripedDst: dstParts.slice(0, i + 1).join("/"),
      };
    }
  }

  return { stripedSrc: "", stripedDst: "" };
}

/**
 * Test if the extension is matched by pattern
 * @param extension extension of a file
 * @param pattern patterns for match extension
 * @returns true if matched, false otherwise
 */
export function matchExtension(extension: string, pattern: string): boolean {
  if (!pattern || pattern === "") return false;
  return new RegExp(pattern).test(extension);
}

/**
 * Check whether the file is an attachment
 * @param settings plugins configuration
 * @param filePath file path
 * @returns true if the file is an attachment, false otherwise
 */
export function isAttachment(settings: AttachmentManagementPluginSettings, filePath: string | TAbstractFile): boolean {
  let file = null;
  if (filePath instanceof TAbstractFile) {
    file = filePath;
  } else {
    file = this.app.vault.getAbstractFileByPath(filePath);
  }

  if (file === null || !(file instanceof TFile)) {
    return false;
  }

  if (isMarkdownFile(file.extension) || isCanvasFile(file.extension)) {
    return false;
  }

  return !matchExtension(file.extension, settings.excludeExtensionPattern);
}

export function getParentFolder(rf: TFile) {
  const parent = rf.parent;
  let parentPath = "/";
  let parentName = "/";
  if (parent) {
    parentPath = parent.path;
    parentName = parent.name;
  }
  return { parentPath, parentName };
}

export async function md5sum(adapter: DataAdapter, file: TFile): Promise<string> {
  const md5 = new Md5();

  if (!adapter.exists(file.path, true)) {
    return "";
  }

  const content = await adapter.readBinary(file.path);
  md5.appendByteArray(new Uint8Array(content));
  const ret = md5.end() as string;

  return ret.toUpperCase();
}

export function validateExtensionEntry(setting: AttachmentPathSettings, plugin: AttachmentManagementPluginSettings) {
  const wrongIndex: {
    type: "empty" | "duplicate" | "md" | "canvas" | "excluded";
    index: number;
  }[] = [];
  if (setting.extensionOverride !== undefined) {
    const extOverride = setting.extensionOverride;
    if (extOverride.some((ext) => ext.extension === "")) {
      wrongIndex.push({ type: "empty", index: extOverride.findIndex((ext) => ext.extension === "") });
    }
    const duplicate = extOverride
      .map((ext) => ext.extension)
      .filter((value, index, self) => self.indexOf(value) !== index);
    if (duplicate.length > 0) {
      duplicate.forEach((dupli) => {
        wrongIndex.push({ type: "duplicate", index: extOverride.findIndex((ext) => dupli === ext.extension) });
      });
    }
    const markdown = extOverride.filter((ext) => ext.extension === "md");
    if (markdown.length > 0) {
      wrongIndex.push({ type: "md", index: extOverride.findIndex((ext) => ext.extension === "md") });
    }
    const canvas = extOverride.filter((ext) => ext.extension === "canvas");
    if (canvas.length > 0) {
      wrongIndex.push({ type: "canvas", index: extOverride.findIndex((ext) => ext.extension === "canvas") });
    }
    const excludedFromSettings = plugin.excludeExtensionPattern.split("|");
    const excluded = extOverride.filter((ext) => excludedFromSettings.includes(ext.extension));
    if (excluded.length > 0) {
      wrongIndex.push({
        type: "excluded",
        index: extOverride.findIndex((ext) => excludedFromSettings.includes(ext.extension)),
      });
    }
  }
  return wrongIndex;
}

export function generateErrorExtensionMessage(type: "md" | "canvas" | "empty" | "duplicate" | "excluded") {
  if (type === "canvas") {
    new Notice(t("errors.canvasNotSupported"));
  } else if (type === "md") {
    new Notice(t("errors.markdownNotSupported"));
  } else if (type === "empty") {
    new Notice(t("errors.extensionEmpty"));
  } else if (type === "duplicate") {
    new Notice(t("errors.duplicateExtension"));
  } else if (type === "excluded") {
    new Notice(t("errors.excludedExtension"));
  }
}
